FROM php:5.6-apache
ADD --chmod=0755 https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN install-php-extensions gd mysql gettext
RUN a2enmod rewrite
RUN a2enmod proxy
RUN a2enmod proxy_http
RUN sed -i "s/AllowOverride None/AllowOverride All/g" /etc/apache2/apache2.conf
RUN rm /etc/apache2/sites-enabled/*
COPY lsboutique.test.conf /etc/apache2/sites-enabled/lsboutique.test.conf
RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"
