source "http://rubygems.org"
gem "rake"
gem "mysql2"
gem "sequel"
gem "dotenv"
# gem 'aws-sdk-s3', '~> 1'
gem "irb"
gem "mail"
gem "redis-namespace"
# gem 'roo'
# gem "oj"
gem "json_pure"
gem "multi_json"
# gem 'nokogiri'
# gem "unicode"
gem "babosa"
gem "sinatra"
gem "sinatra-contrib"
gem "sinatra-cross_origin"
gem "roda"
gem "puma"
# gem 'ruby-trello'
gem "sanitize"
# gem 'fcm'
gem "slim"
gem "smarter_csv"
gem "slack-api"
gem "mailgun-ruby"
# gem 'axlsx'
gem "zip-zip"
gem "bugsnag"
gem "washbullet"
# gem "celluloid", "0.16.0"
gem "httparty"
gem "sidekiq"
gem "sidekiq-cron"
gem "sidekiq-rate-limiter"
gem "rubykiq"
# gem "mechanize"
gem "builder"
# gem 'google_drive'
gem "phonelib"
# gem "dropbox-sdk-v2"
gem "addressable"
gem "gibbon"
gem "remote_syslog_logger"
gem "rotp"
gem "redlock"
gem "base32"
gem "rspec"
gem "sysrandom"
gem "pusher"
gem "twisted-caldav"
gem "uuid"
gem "nori"
gem "http"
gem "rexml"

# group :development do
# gem "rerun", git: "https://github.com/alexch/rerun"
# end
