INSERT INTO `warehouses` (`name`, `code`, `movement_enabled`) VALUES ('склад №1', 7, 1);
INSERT INTO `warehouses` (`name`, `code`, `movement_enabled`) VALUES ('Luxury Store (НВН)', 13, 1);
INSERT INTO `warehouses` (`name`, `code`, `movement_enabled`) VALUES ('Luxury Store (Этажи)', 14, 1);
INSERT INTO `warehouses` (`name`, `code`, `movement_enabled`) VALUES ('Лакшери Покровка', 15, 1);
INSERT INTO `warehouses` (`name`, `code`, `movement_enabled`) VALUES ('Лакшери Этажи', 16, 1);
INSERT INTO `warehouses` (`name`, `code`, `movement_enabled`) VALUES ('Out Let', 17, 1);
INSERT INTO `warehouses` (`name`, `code`, `movement_enabled`) VALUES ('Склад', 18, 1);
INSERT INTO `warehouses` (`name`, `code`, `movement_enabled`) VALUES ('Ice Iceberg', 19, 1);
INSERT INTO `warehouses` (`name`, `code`, `movement_enabled`) VALUES ('Podium VIP', 20, 1);
INSERT INTO `warehouses` (`name`, `code`, `movement_enabled`) VALUES ('Интернет-магазин', 21, 1);
INSERT INTO `warehouses` (`name`, `code`, `movement_enabled`) VALUES ('Жехаревы', 30, 1);
INSERT INTO `warehouses` (`name`, `code`, `movement_enabled`) VALUES ('Ценники', 31, 1);
INSERT INTO `warehouses` (`name`, `code`, `movement_enabled`) VALUES ('Брак', 32, 1);
INSERT INTO `warehouses` (`name`, `code`, `movement_enabled`) VALUES ('SALE Online shop', 40, 1);
INSERT INTO `warehouses` (`name`, `code`, `movement_enabled`) VALUES ('SALE Online shop НВН', 41, 1);
INSERT INTO `warehouses` (`name`, `code`, `movement_enabled`) VALUES ('SALE Online shop Out Let', 42, 1);
INSERT INTO `warehouses` (`name`, `code`, `movement_enabled`) VALUES ('SALE Online shop Лакшери Покровка', 43, 1);
INSERT INTO `warehouses` (`name`, `code`, `movement_enabled`) VALUES ('Лакшери Покровка 50', 44, 1);
INSERT INTO `warehouses` (`name`, `code`, `movement_enabled`) VALUES ('Лакшери Покровка 50-2этаж', 45, 1);
INSERT INTO `warehouses` (`name`, `code`, `movement_enabled`) VALUES ('Лакшери Покровка 50-3этаж', 46, 1);
INSERT INTO `warehouses` (`name`, `code`, `movement_enabled`) VALUES ('Доставка СДЭК', 33, 1);
INSERT INTO `warehouses` (`name`, `code`, `movement_enabled`) VALUES ('Доставка Пони Экспресс', 34, 1);
INSERT INTO `warehouses` (`name`, `code`, `movement_enabled`) VALUES ('Доставка СПСР', 35, 1);
INSERT INTO `warehouses` (`name`, `code`, `movement_enabled`) VALUES ('Доставка DHL', 36, 1);
INSERT INTO `warehouses` (`name`, `code`, `movement_enabled`) VALUES ('Доставка Нижний Новгород', 37, 1);
INSERT INTO `warehouses` (`name`, `code`, `movement_enabled`) VALUES ('Доставка по Москве', 39, 1);
INSERT INTO `warehouses` (`name`, `code`, `movement_enabled`) VALUES ('Отложка LS(НВН)', 23, 1);
INSERT INTO `warehouses` (`name`, `code`, `movement_enabled`) VALUES ('Отложка Подиум', 24, 1);
INSERT INTO `warehouses` (`name`, `code`, `movement_enabled`) VALUES ('Отложка Out Let', 25, 1);
INSERT INTO `warehouses` (`name`, `code`, `movement_enabled`) VALUES ('Отложка LS(Этажи)', 26, 1);
INSERT INTO `warehouses` (`name`, `code`, `movement_enabled`) VALUES ('Отложка Подиум VIP', 27, 1);
INSERT INTO `warehouses` (`name`, `code`, `movement_enabled`) VALUES ('Отложка Iceberg', 28, 1);
INSERT INTO `warehouses` (`name`, `code`, `movement_enabled`) VALUES ('Отложка Ramsey', 29, 1);
INSERT INTO `warehouses` (`name`, `code`, `movement_enabled`) VALUES ('RAMSEY (Республика)', 4, 1);
INSERT INTO `warehouses` (`name`, `code`, `movement_enabled`) VALUES ('Cток', 6, 1);
INSERT INTO `warehouses` (`name`, `code`, `movement_enabled`) VALUES ('Out Let розница', 10, 1);
INSERT INTO `warehouses` (`name`, `code`, `movement_enabled`) VALUES ('Luxury Store (НВН) опт', 1, 1);
INSERT INTO `warehouses` (`name`, `code`, `movement_enabled`) VALUES ('Luxury Store (Этажи) опт', 2, 1);
INSERT INTO `warehouses` (`name`, `code`, `movement_enabled`) VALUES ('RAMSEY опт', 3, 1);
INSERT INTO `warehouses` (`name`, `code`, `movement_enabled`) VALUES ('ПОДИУМ опт', 5, 1);
INSERT INTO `warehouses` (`name`, `code`, `movement_enabled`) VALUES ('Склад опт', 8, 1);
INSERT INTO `warehouses` (`name`, `code`, `movement_enabled`) VALUES ('Out Let опт', 9, 1);
