// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 2.2.3
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
function ws_basic(c,a,b){this.go=function(d){b.find("ul").stop(true).animate({left:(d?-d+"00%":0)},c.duration,"swing");return d}};// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 2.2.3
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery("#wowslider-container2").wowSlider({effect:"basic",prev:"",next:"",duration:10*100,delay:60*100,width:456,height:161,autoPlay:true,stopOnHover:false,loop:false,bullets:false,caption:false,controls:false,logo:"",images:0});
jQuery("#wowslider-container3").wowSlider({effect:"basic",prev:"",next:"",duration:10*100,delay:60*100,width:456,height:161,autoPlay:true,stopOnHover:false,loop:false,bullets:false,caption:false,controls:false,logo:"",images:0});
